# Obtained from https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages
# Modified to suit this deployment, all credit goes to the yaml original creator
name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code from the main branch
      - uses: actions/checkout@v2

      # sets up .NET SDK 6.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0

      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish portfolio.csproj -c Release -o release --nologo

      # changes the base-tag in index.html from '/' to 'portfolio' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to portfolio
        run: sed -i 's/<base href="\/" \/>/<base href="\/portfolio\/" \/>/g' release/wwwroot/index.html

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ github.token }}
          branch: gh-pages
          folder: release/wwwroot
